[package]
name = "move_window"
version = "0.3.1"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]
edition = "2018"

[dependencies]
cocoa = "0.19.0"
core-foundation = "0.10"
core-graphics = "0.24.0"
objc = "0.2.5"
