[package]
name = "move_window"
version = "0.3.1"
authors = ["Holger Rapp <HolgerRapp@gmx.net>"]
edition = "2018"

[dependencies]
objc = "0.2.5"
core-foundation = "0.10"
cocoa = "0.19.0"
serde_derive = "1.0.89"
serde = "1.0.89"
core-graphics = "0.24.0"
serde_json = "1.0.140"
