#!/usr/bin/env python
# encoding: utf-8

import argparse
import re
import subprocess
from sys import exit

import _mw_helper

import appscript as AS

def parse_args():
    parser = argparse.ArgumentParser(description='Move windows via AppleEvents')
    parser.add_argument('cmd', type=str, default="0",
                       help='<screen=0><xratio=1><xpos=0[-ypos]><yratio=1><ypos=0[-ypos]>')
    parser.add_argument('-L','--left-limit',type=int,default=0,dest='left_limit',
                       help='sets the left-hand limit (in pixels) so that windows do not get moved under a left-side dock')

    return parser.parse_args()

def move_window(x, y, w, h):
    capp_name = _mw_helper.frontmost_process()
    app = AS.Application(capp_name)
    try:
        app.windows[1].position.set((x, y))
        app.windows[1].size.set((w, h))
    except (AttributeError, AS.reference.CommandError) as err:
        app.windows[1].bounds.set((x, y, x + w, y + h))

def main():
    cmd = parse_args().cmd
    left_limit = parse_args().left_limit
    res = _mw_helper.get_resolutions()

    screen, cmd = (0, cmd) if not cmd else (int(cmd[0]), cmd[1:])
    xratio, cmd = (1, cmd) if not cmd else (int(cmd[0]), cmd[1:])
    xpos_s, cmd = (0, cmd) if not cmd else (int(cmd[0]), cmd[1:])
    xpos_e = xpos_s
    if cmd and cmd[0] == '-':
        xpos_e, cmd = (int(cmd[1]), cmd[2:])
    yratio, cmd = (1, cmd) if not cmd else (int(cmd[0]), cmd[1:])
    ypos_s, cmd = (0, cmd) if not cmd else (int(cmd[0]), cmd[1:])
    ypos_e = ypos_s
    if cmd and cmd[0] == '-':
        ypos_e, cmd = (int(cmd[1]), cmd[2:])

    if screen == 0:
        x, y = 0, 22
        res[0][1] -= 22
    else:
        try:
            x = -res[1][0]
            y = 0
            left_limit = 0
        except IndexError:
            if len(res)<=screen:
                print "Your screen(s):"
                for residx in range(len(res)):
                    print "   [{0}]: {1} x {2}".format(residx,res[residx][0],res[residx][1])
                print "Tried to move window to screen {0}, but it does not exist.".format(screen)
                exit()

    assert(screen in [0,1])

    one_width = ((res[screen][0] - left_limit) / xratio)
    one_height = (res[screen][1] / yratio)

    w = one_width * (xpos_e - xpos_s + 1)
    h = one_height * (ypos_e - ypos_s + 1)
    x += one_width * xpos_s + left_limit
    y += one_height * ypos_s

    move_window(x, y, w, h)



if __name__ == '__main__':
    main()
